[package]
name = "jim"
version = "0.1.0"
authors = ["Nathaniel Cook <nvcook42@gmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
name = "repl"

[dependencies]
peg = "0.6"
anyhow = "1.0"
